### ISSUE TITLE
Gradle task runAntlrKey does not declare its dependencies correctly

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#3915]
## Description

The Gradle task of parser generation for the `KeYJavaParser` is not correctly set-up, especially, the imported grammars are not declared as inputs. 

This leads to the problem, that this task is not correctly re-executed. Leading to annyoing exceptions: 

```
* What went wrong:
Execution failed for task ':key.core:compileJava' (registered by plugin class 'org.gradle.api.plugins.JavaBasePlugin').
> Compilation failed; see the compiler output below.
  /home/weigl/work/key-main/key.core/src/main/java/de/uka/ilkd/key/nparser/builder/TacletPBuilder.java:196: error: cannot find symbol
          if (!ctx.IGNOREUPDATELEVEL().isEmpty() && !ctx.SAMEUPDATELEVEL().isEmpty()) {
                  ^
    symbol:   method IGNOREUPDATELEVEL()
    location: variable ctx of type TacletContext
  4 errors
```

Introduced by #3822 

## Reproducible
  
always

### Steps to reproduce 

1. Run `gradle testClasses`
1. Make a change in an imported grammar file. This needs to resolve into a compiler error.
2. Run `gradle testClasses`

   Observe that it still compiles. 

> What is your expected behavior and what was the actual behavior?

Compile error.

### Additional information

Branch: `main` 75f0a043fe843e936a86bf295d883ec1d5598a2e

---

* Commit: 75f0a043fe843e936a86bf295d883ec1d5598a2e

**Comment by Drodt** [comment]
I can't seem to reproduce this.

**Comment by wadoon** [comment]
Complete command list: 

```sh
loewenheim ~/w/key-main % git switch main; 
loewenheim ~/w/key-main % git pull 
loewenheim ~/w/key-main % gradle classes --parallel
.....
BUILD SUCCESSFUL in 54s
37 actionable tasks: 37 executed
loewenheim ~/w/key-main % wc -l key.ncore/src/main/antlr/KeYTacletParser.g4
133 key.ncore/src/main/antlr/KeYTacletParser.g4
loewenheim ~/w/key-main % echo >  key.ncore/src/main/antlr/KeYTacletParser.g4
loewenheim ~/w/key-main % wc -l key.ncore/src/main/antlr/KeYTacletParser.g4
1 key.ncore/src/main/antlr/KeYTacletParser.g4
loewenheim ~/w/key-main % gradle classes --parallel

> Configure project :
No android or java plugins found in the project key-main, checker compiler options will not be applied.

[Incubating] Problems report is available at: file:///home/weigl/work/key-main/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/9.6.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 1s
37 actionable tasks: 37 up-to-date
```

It should not succeed. I killed the grammar!

**Comment by wadoon** [comment]
Not fixed correctly. The correct task would be defined here: 

https://github.com/KeYProject/key/blob/3ef3ce1a9f66b1d7f280be81e1ca4eb7fa236da7/key.core/build.gradle#L193

The ugly problem is to define dependencies accross modules. 

Steps to reproduce: 

1. Compile
2. Destroy `KeYParser.g4´ 
   ```antlr4
   parser grammar KeYParser;
   eof:EOF;
   ```
3. `gradle classes`

   `ncore` is recompiled w/o error as `KeYParser.g4` is not used there. 
   
   `core` is not regenerated and recompiled.
