### PR TITLE
Fix file dependency for runAntlr4KeY

### LINKED ISSUE #3915: Gradle task runAntlrKey does not declare its dependencies correctly
## Description

The Gradle task of parser generation for the `KeYJavaParser` is not correctly set-up, especially, the imported grammars are not declared as inputs. 

This leads to the problem, that this task is not correctly re-executed. Leading to annyoing exceptions: 

```
* What went wrong:
Execution failed for task ':key.core:compileJava' (registered by plugin class 'org.gradle.api.plugins.JavaBasePlugin').
> Compilation failed; see the compiler output below.
  /home/weigl/work/key-main/key.core/src/main/java/de/uka/ilkd/key/nparser/builder/TacletPBuilder.java:196: error: cannot find symbol
          if (!ctx.IGNOREUPDATELEVEL().isEmpty() && !ctx.SAMEUPDATELEVEL().isEmpty()) {
                  ^
    symbol:   method IGNOREUPDATELEVEL()
    location: variable ctx of type TacletContext
  4 errors
```

Introduced by #3822 

## Reproducible
  
always

### Steps to reproduce 

1. Run `gradle testClasses`
1. Make a change in an imported grammar file. This needs to resolve into a compiler error.
2. Run `gradle testClasses`

   Observe that it still compiles. 

> What is your expected behavior and what was the actual behavior?

Compile error.

### Additional information

Branch: `main` 75f0a043fe843e936a86bf295d883ec1d5598a2e

---

* Commit: 75f0a043fe843e936a86bf295d883ec1d5598a2e

### PR DESCRIPTION
**Pull request by Drodt**
## Related Issue

This pull request resolves #3915.

## Intended Change

Adds all ANTLR files to the task's dependencies. 

## Type of pull request

- Bug fix (non-breaking change which fixes an issue)
- There are changes to the deployment/CI infrastructure (gradle, github, ...)

## Ensuring quality

   
- I have tested the feature as follows: Tested it with the setup of #3915

## Additional information and contact(s)

     

The contributions within this pull request are licensed under GPLv2 (only) for inclusion in KeY.

### CODE REVIEW

**Review by unp1 — APPROVED** [review]
Thanks!
